SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(c.SALES*b.PRICE) AS TOTAL_SALES
FROM AUTHOR a
JOIN BOOK b ON a.AUTHOR_ID = b.AUTHOR_ID
JOIN BOOK_SALES c ON b.BOOK_ID = c.BOOK_ID
WHERE DATE_FORMAT(c.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY a.AUTHOR_ID,a.AUTHOR_NAME,b.CATEGORY
ORDER BY a.AUTHOR_ID ASC, b.CATEGORY DESC;
