SELECT 
  a.CAR_ID,
  a.CAR_TYPE,
  ROUND(a.DAILY_FEE * 30 * (1 - b.DISCOUNT_RATE / 100)) AS FEE
FROM 
  CAR_RENTAL_COMPANY_CAR a
INNER JOIN 
  CAR_RENTAL_COMPANY_DISCOUNT_PLAN b ON a.CAR_TYPE = b.CAR_TYPE
WHERE 
  a.CAR_TYPE IN ('세단', 'SUV')
  AND a.CAR_ID NOT IN (
    SELECT 
      c.CAR_ID 
    FROM 
      CAR_RENTAL_COMPANY_RENTAL_HISTORY c
    WHERE 
      c.START_DATE <= '2022-11-30' 
      AND c.END_DATE >= '2022-11-01'
  )
  AND b.DURATION_TYPE = '30일 이상'
  HAVING FEE >=500000 AND FEE<2000000
ORDER BY 
  FEE DESC, a.CAR_TYPE ASC, a.CAR_ID DESC;
