-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE)AS MONTH, GENDER, COUNT(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO a
JOIN ONLINE_SALE b
ON a.USER_ID = b.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC;