-- 코드를 입력하세요
SELECT a.USER_ID,a.NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER a
JOIN USED_GOODS_BOARD ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
GROUP BY a.USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;