SELECT MEMBER_NAME,REVIEW_TEXT,DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE a
JOIN REST_REVIEW b ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW GROUP BY MEMBER_ID HAVING COUNT(MEMBER_ID) ORDER BY COUNT(MEMBER_ID) DESC limit 1)
ORDER BY 3 asc,2 asc;
