WITH RANKED_PRODUCTS AS (
    SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
)
SELECT a.CATEGORY, a.PRICE, a.PRODUCT_NAME
FROM FOOD_PRODUCT a
JOIN RANKED_PRODUCTS b ON a.CATEGORY = b.CATEGORY AND a.PRICE = b.MAX_PRICE
ORDER BY a.PRICE DESC;
